version: "3.9"

services:
  watcher-bot:
    build: .
    container_name: watcher-bot
    volumes:
      - cache:/app/data
    restart: always             # автоперезапуск при сбоях
    environment:
      TOKEN: ${TOKEN}
      TZ: "Europe/Moscow"

volumes:
  cache: