version: "3.9"

services:
  watcher-bot:
    build: .
    container_name: watcher-bot
    volumes:
      - ./data:/app/data        # data.json сохранится тут
    restart: always             # автоперезапуск при сбоях
    environment:
      TOKEN: ${TOKEN}
      TZ: "Europe/Moscow"
